name: Build and Push Docker Image

on:
  push:
    branches:
    - main
jobs:
  build-and-push:
    name: Build, Test, and Push Docker Image
    runs-on: ubuntu-latest

   
    permissions:
      contents: read
      packages: write # Required for pushing to GHCR

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ vars.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    # Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry (GHCR)
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Debug Secrets
      run: |
       echo "DOCKER_HUB_USERNAME: ${{ vars.DOCKER_HUB_USERNAME }}"
      
    # Build Docker Image
    - name: Build Docker Image
      run: |
        docker build -t ${{ vars.DOCKER_HUB_USERNAME }}/dummy-python-app:latest .
        docker tag ${{ vars.DOCKER_HUB_USERNAME }}/dummy-python-app:latest ghcr.io/${{ github.repository_owner }}/dummy-python-app:latest

    # Test the Docker Image
    - name: Test Docker Image
      run: |
        # Run container in detached mode
        docker run -d -p 5000:5000 --name dummy-app-test ${{ vars.DOCKER_HUB_USERNAME }}/dummy-python-app:latest
        # Wait for the app to start
        sleep 5
        # Test endpoints
        curl -f http://localhost:5000/ || exit 1
        curl -f http://localhost:5000/health || exit 1
        # Stop the container after testing
        docker stop dummy-app-test
        docker rm dummy-app-test

    # Push to Docker Hub
    - name: Push Docker Image to Docker Hub
      run: |
        docker push ${{ vars.DOCKER_HUB_USERNAME }}/dummy-python-app:latest

    # Push to GitHub Container Registry
    - name: Push Docker Image to GHCR
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/dummy-python-app:latest
